alias ga='git add'
alias gall='git add --all .'
alias gamend='git commit --amend'
alias gamendh='git commit --all --amend --no-edit'
alias gap='git add --patch'
alias gashc='git stash clear'
alias gau='git add --update'
alias gb='git branch --verbose'
alias gba='git branch --all'
alias gbi='git bisect'
alias gbib='git bisect bad'
alias gbig='git bisect good'
alias gbih='git bisect help'
alias gbil='git bisect log'
alias gbir='git bisect reset'
alias gbire='git bisect replay'
alias gbis='git bisect start'
alias gbisk='git bisect skip'
alias gbiv='git bisect visualize --reverse --pretty=format:"%C(yellow)%H%C(reset) %C(bold blue)%an%C(reset) %s%C(bold cyan)%d%C(reset) %C(green)(%cr)%C(reset)"'
alias gbn='_git_branch_name | _copy_and_print'
alias gbr='git branch --move'
alias gbt='git show-branch --topics'
alias gca='git commit --all'
alias gcam='git commit --all --message'
alias gcf='git commit --fixup'
alias gcge='git config --global --edit'
alias gch='git checkout'
alias gchm='git checkout master'
alias gcl='git clone'
alias gcle='git config --local --edit'
alias gcm='git commit --message'
alias gco='git commit'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcs='git commit --squash'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdis='git reset --hard'
alias gdm='git diff origin/master'
alias gdt='git difftool'
alias gdtc='git difftool --cached'
alias gdtm='git difftool origin/master'
alias gdw='git diff --color-words'
alias gel='git rm'
alias gelc='git rm --cached'
alias ger='git rerere'
alias gf='git fetch'
alias gfp='git fetch --prune'
alias gg='git grep'
alias gget='git config'
alias gi='git init'
alias gl='git log --graph --pretty=format:"%C(yellow)%H%C(reset) %C(bold blue)%an%C(reset) %s%C(bold cyan)%d%C(reset) %C(green)(%cr)%C(reset)"'
alias glame='git blame'
alias glast='git show --decorate --stat'
alias glatest='git for-each-ref --sort=-committerdate refs/heads --format='\''%(committerdate:short) %(refname:short)'\'''
alias gld='git log --stat --pretty=format:"%C(yellow)%H%C(reset) %C(bold blue)%an%C(reset) %s%C(bold cyan)%d%C(reset) %C(green)(%cr)%C(reset) %n%b"'
alias glf='git fetch && git log --reverse --no-merges --pretty=format:"%C(yellow)%H%C(reset) %C(bold blue)%an%C(reset) %s%C(bold cyan)%d%C(reset) %C(green)(%cr)%C(reset)" ..@{upstream}'
alias glg='git log --pretty=format:"%C(yellow)%H%C(reset) %C(bold blue)%an%C(reset) %s%C(bold cyan)%d%C(reset) %C(green)(%cr)%C(reset)" --grep'
alias glh='git log --pretty=format:%H -1 | _copy_and_print'
alias gls='git log --pretty=format:"%C(yellow)%H%C(reset) %C(bold blue)%an%C(reset) %s%C(bold cyan)%d%C(reset) %C(green)(%cr)%C(reset)" -S'
alias glt='git log --tags --simplify-by-decoration --reverse --pretty="format:%d (%ad)" --date=short | sed -e "s/ (tag: //" -e "s/)//" -e "/^ /d"'
alias gm='git merge'
alias gma='git merge --abort'
alias gms='git merge --squash'
alias gp='git push'
alias gpn='git push --no-verify'
alias gpo='git push --set-upstream origin'
alias gpp='git push production production:master'
alias gpr='git push review master'
alias gps='git push stage stage:master'
alias gpu='git pull'
alias gpur='git pull --rebase'
alias gpuro='gpur origin'
alias gpurom='gpuro master'
alias gr='git reset'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias grev='git revert'
alias grh='git reset --hard HEAD'
alias grl='git reflog'
alias grm='git reset --merge ORIG_HEAD'
alias grom='git fetch --all && git reset --hard origin/master'
alias grp='git remote prune origin'
alias grs='git reset --soft HEAD^'
alias gst='git status --short --branch'
alias gtag='git tag'
alias gtags='git push --tags'
alias guthors='git log --format='\''%an'\'' | sort | uniq -c | sort --reverse'
